from __future__ import annotations

import json
import os
import plistlib
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

from .core import SkillMagnetError


@dataclass(frozen=True)
class ContextMenuSpec:
    platform: str
    integration: str
    menu_label: str
    selected_path_placeholder: str
    command: tuple[str, ...]

    def as_dict(self) -> dict[str, object]:
        return {
            "platform": self.platform,
            "integration": self.integration,
            "menu_label": self.menu_label,
            "selected_path_placeholder": self.selected_path_placeholder,
            "command": list(self.command),
            "automatic_activation": False,
            "required_flow": [
                "open_context_menu",
                "choose_skill_magnet",
                "explicitly_select_pack",
                "confirm_target_version_and_purpose",
                "launch",
            ],
        }


def context_menu_spec(platform: str, config: Path) -> ContextMenuSpec:
    prefix = (sys.executable, "-m", "skill_magnet", "--config", str(config.resolve()))
    if platform == "windows":
        placeholder = "%V"
        return ContextMenuSpec(
            platform="windows",
            integration="windows_explorer_context_menu",
            menu_label="Skill Magnet...",
            selected_path_placeholder=placeholder,
            command=(*prefix, "context", "--platform", "windows", "--project", placeholder),
        )
    if platform == "macos":
        placeholder = "$SELECTED_PATH"
        return ContextMenuSpec(
            platform="macos",
            integration="macos_finder_quick_action",
            menu_label="Skill Magnet...",
            selected_path_placeholder=placeholder,
            command=(*prefix, "context", "--platform", "macos", "--project", placeholder),
        )
    raise SkillMagnetError(f"Unsupported platform: {platform}")


def render_registration(platform: str, config: Path) -> str:
    spec = context_menu_spec(platform, config)
    if platform == "windows":
        background_command = subprocess_command(spec.command)
        directory_command = background_command.replace("%V", "%1")
        sections: list[str] = ["Windows Registry Editor Version 5.00\n"]
        for key, command in (
            (
                "HKEY_CURRENT_USER\\Software\\Classes\\Directory\\shell\\SkillMagnet",
                directory_command,
            ),
            (
                "HKEY_CURRENT_USER\\Software\\Classes\\Directory\\Background\\shell\\SkillMagnet",
                background_command,
            ),
        ):
            sections.extend(
                [
                    f"[{key}]\n",
                    '"MUIVerb"="Skill Magnet..."\n\n',
                    f"[{key}\\command]\n",
                    f'@="{command.replace(chr(34), chr(92) + chr(34))}"\n',
                ]
            )
        return "\n".join(sections)
    payload = json.dumps(spec.as_dict(), ensure_ascii=False, sort_keys=True)
    return (
        "#!/bin/sh\n"
        "# Finder Quick Action adapter generated by Skill Magnet.\n"
        f"SKILL_MAGNET_SPEC='{payload}'\n"
        'SELECTED_PATH="$1"\n'
        + subprocess_command(spec.command)
        + "\n"
    )


def subprocess_command(parts: tuple[str, ...]) -> str:
    def quote(value: str) -> str:
        return '"' + value.replace('"', '\\"') + '"'

    return " ".join(quote(part) for part in parts)


def install_context_menu(
    platform: str,
    config: Path,
    *,
    services_dir: Path | None = None,
    run: object = subprocess.run,
) -> dict[str, object]:
    """Install only after an explicit CLI request; never activates a pack."""
    spec = context_menu_spec(platform, config)
    if platform == "windows":
        if os.name != "nt":
            raise SkillMagnetError("Windows context menu can only be installed on Windows")
        base_command = subprocess_command(spec.command)
        roots = (
            (r"HKCU\Software\Classes\Directory\shell\SkillMagnet", base_command.replace("%V", "%1")),
            (r"HKCU\Software\Classes\Directory\Background\shell\SkillMagnet", base_command),
        )
        try:
            for root, command in roots:
                for args in (
                    ["reg", "add", root, "/ve", "/d", "Skill Magnet...", "/f"],
                    ["reg", "add", root + r"\command", "/ve", "/d", command, "/f"],
                ):
                    result = run(args, capture_output=True, text=True)
                    if result.returncode != 0:
                        raise SkillMagnetError(
                            f"Cannot install Windows context menu: {result.stderr.strip()}"
                        )
        except Exception:
            for root, _ in roots:
                run(["reg", "delete", root, "/f"], capture_output=True, text=True)
            raise
        return {
            "installed": True,
            "platform": platform,
            "locations": [root for root, _ in roots],
        }

    if sys.platform != "darwin" and services_dir is None:
        raise SkillMagnetError("Finder Quick Action can only be installed on macOS")
    base = services_dir or (Path.home() / "Library" / "Services")
    base_preexisting = base.exists()
    base.mkdir(parents=True, exist_ok=True)
    workflow_root = base / "Skill Magnet.workflow"
    if workflow_root.exists():
        raise SkillMagnetError(f"Finder Quick Action already exists: {workflow_root}")
    temporary_root = Path(tempfile.mkdtemp(prefix=".skill-magnet-workflow-", dir=base))
    workflow = temporary_root / "Contents"
    workflow.mkdir()
    shell_command = subprocess_command(spec.command).replace('"$SELECTED_PATH"', '"$1"')
    document = {
        "AMApplicationBuild": "SkillMagnet",
        "AMApplicationVersion": "1",
        "AMDocumentVersion": "2",
        "actions": [
            {
                "action": {
                    "AMAccepts": {"Container": "List", "Optional": True, "Types": ["com.apple.cocoa.path"]},
                    "AMActionVersion": "2.0.3",
                    "AMParameterProperties": {},
                    "AMProvides": {"Container": "List", "Types": ["com.apple.cocoa.path"]},
                    "BundleIdentifier": "com.apple.RunShellScript",
                    "CFBundleVersion": "2.0.3",
                    "Class Name": "RunShellScriptAction",
                    "parameters": {
                        "COMMAND_STRING": shell_command,
                        "CheckedForUserDefaultShell": True,
                        "inputMethod": 1,
                        "shell": "/bin/zsh",
                    },
                }
            }
        ],
        "connectors": {},
        "workflowMetaData": {
            "serviceInputTypeIdentifier": "com.apple.finder.file-or-folder",
            "serviceOutputTypeIdentifier": "com.apple.Automator.nothing",
            "serviceProcessesInput": 0,
            "serviceApplicationBundleID": "com.apple.finder",
        },
    }
    try:
        with (workflow / "document.wflow").open("wb") as handle:
            plistlib.dump(document, handle)
        os.replace(temporary_root, workflow_root)
    except Exception:
        shutil.rmtree(temporary_root, ignore_errors=True)
        if not base_preexisting:
            try:
                base.rmdir()
            except OSError:
                pass
        raise
    return {
        "installed": True,
        "platform": platform,
        "locations": [str(workflow_root)],
    }


def uninstall_context_menu(
    platform: str,
    *,
    services_dir: Path | None = None,
    run: object = subprocess.run,
) -> dict[str, object]:
    if platform == "windows":
        if os.name != "nt":
            raise SkillMagnetError("Windows context menu can only be removed on Windows")
        roots = (
            r"HKCU\Software\Classes\Directory\shell\SkillMagnet",
            r"HKCU\Software\Classes\Directory\Background\shell\SkillMagnet",
        )
        for root in roots:
            result = run(["reg", "delete", root, "/f"], capture_output=True, text=True)
            if result.returncode not in (0, 1):
                raise SkillMagnetError(
                    f"Cannot remove Windows context menu: {result.stderr.strip()}"
                )
        return {"removed": True, "platform": platform, "locations": list(roots)}
    if sys.platform != "darwin" and services_dir is None:
        raise SkillMagnetError("Finder Quick Action can only be removed on macOS")
    base = services_dir or (Path.home() / "Library" / "Services")
    workflow = base / "Skill Magnet.workflow"
    if workflow.exists():
        shutil.rmtree(workflow)
    return {"removed": True, "platform": platform, "locations": [str(workflow)]}
